[package]
name = "pi_spine_rs"
version = "0.0.1"
authors = ["baip0002 <2494156981@qq.com>"]
edition = "2021"
description = "Pi Spine Render."
repository = "https://github.com/GaiaWorld/pi_spine_rs"
license = "MIT OR Apache-2.0"
keywords = ["scene Render"]

[dependencies]
wgpu = { version = "0.12", features = ["spirv", "glsl"] }
approx = "0.5"
naga = { version = "0.8", features = [
    "glsl-in",
    "spv-in",
    "spv-out",
    "wgsl-in",
    "wgsl-out",
] }
bytemuck = { version = "1.4", features = ["derive"] }
pi_slotmap = "0.1"
pi_hash="0.1"

pi_animation = { git = "https://github.com/GaiaWorld/pi_animation" }

render_pipeline_key = { git = "https://github.com/GaiaWorld/pi_render" }
render_data_container = { git = "https://github.com/GaiaWorld/pi_render" }
render_geometry = { git = "https://github.com/GaiaWorld/pi_render" }
render_material = { git = "https://github.com/GaiaWorld/pi_render" }
pi_render = { git = "https://github.com/GaiaWorld/pi_render" }

[patch."https://github.com/GaiaWorld/pi_animation"]
pi_animation = { path = "../pi_animation" }

[patch."https://github.com/GaiaWorld/pi_render"]
pi_render = { path = "../pi_render" }

# [[example]]

[dev-dependencies]
image = "0.24"
env_logger = "0.9"
winit = "0.26"
pollster = "0.2"
